name: Go CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install C++ toolchain
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Build C++ core
      run: make -C vemu_service/cgo_bridge

    - name: Run C++ tests
      run: |
        # 编译所有 C++ 测试目标（Makefile 已定义 PHONY 目标）
        make -C vemu_service/cgo_bridge \
          test_trap test_mem \
          test_decoder_branch test_decoder_jal test_decoder_jalr \
          test_decoder_csr test_decoder_i test_decoder_m
        # 逐个执行生成的测试可执行文件
        for t in vemu_service/cgo_bridge/test_*; do
          echo "Running $t";
          $t;
        done

    - name: Build
      env:
        CGO_ENABLED: 1
      run: go build -tags cgo -v ./...

    - name: Test
      env:
        CGO_ENABLED: 1
      run: go test -tags cgo -v ./... 