name: Go CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install C++ toolchain
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Build C++ core
      run: make -C vemu_service/cgo_bridge

    - name: Build
      env:
        CGO_ENABLED: 1
      run: go build -tags cgo -v ./...

    - name: Test
      env:
        CGO_ENABLED: 1
      run: go test -tags cgo -v ./... 